server:
  port: 8001

spring:
  application:
    name: feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: false
  client:
    config:
      # 默认配置
      default:
        readTimeout: 1000
        loggerLevel: BASIC
      # 指定 feignClient 配置
      feign-producer:
        readTimeout: 500

# ribbon 超时（不推荐）
#ribbon:
#  ReadTimeout: 2000

# 搭配 loggerLevel 输出 feign 日志
logging:
  level:
    io.zhenye.feign.consumer.feign: DEBUG