server:
  shutdown: graceful

spring:
  application:
    name: spring-boot

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
#    fetch-registry: true
#    registry-fetch-interval-seconds: 8
  instance:
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 4
#    lease-expiration-duration-in-seconds: 12

#management:
#  endpoint:
#    env:
#      post:
#        enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: shutdown