server:
  port: 9001
  shutdown: graceful

spring:
  application:
    name: feign-producer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: service-registry